# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'TouchLock' do
   pod 'VENTouchLock', '~> 1.0.6'
   pod 'SSToolkit', '~> 2.0.0'
   pod 'SSKeychain', '~> 1.2.3'
end

target 'TouchLockTests' do

end

