# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ScrollView撑大机理' do
pod 'Masonry'
end

target 'ScrollView撑大机理Tests' do

end

target 'ScrollView撑大机理UITests' do

end

